export type RewardType = "facts" | "questionsAnswers" | "flags" | "randomFactWidget" | "quoteOfTheDayWidget" | "vocabulary";

export interface QuestionAnswerReward {
  question: string;
  answer: string;
}

export interface FlagReward {
  countryName: string;
  flagCode: string; // e.g., 'de', 'us', 'al'
}

export interface VocabularyReward {
  question: string;
  answer: string;
}

export interface Reward {
  type: RewardType;
  content: string | QuestionAnswerReward | FlagReward | VocabularyReward | null; // content can be null for widgets
}

const allFacts: string[] = [
  "Wussten Sie, dass die Chinesische Mauer nicht vom Mond aus sichtbar ist?",
  "Die kürzeste Kriegsgeschichte dauerte nur 38 Minuten (zwischen Großbritannien und Sansibar im Jahr 1896).",
  "Kleopatra lebte näher an der Erfindung des iPhones als am Bau der Pyramiden.",
  "Das Römische Reich existierte länger als die Vereinigten Staaten bisher.",
  "Die erste aufgezeichnete Verwendung des Wortes 'OK' war 1839 in einer Bostoner Zeitung.",
  "Die Pyramiden von Gizeh wurden gebaut, als Mammuts noch lebten.",
  "Die Wikinger benutzten Sonnensteine, um an bewölkten Tagen zu navigieren.",
  "Die älteste bekannte Melodie ist ein 3.400 Jahre altes Lied aus Ugarit, Syrien.",
  "Die erste Kamera benötigte 8 Stunden Belichtungszeit für ein einziges Bild.",
  "Im antiken Rom war Purpur die Farbe der Kaiser und Senatoren, da der Farbstoff extrem teuer war.",
  "Die Bibliothek von Alexandria war eine der größten und bedeutendsten Bibliotheken der Antike.",
  "Die erste gedruckte Bibel wurde von Johannes Gutenberg im 15. Jahrhundert hergestellt.",
  "Die Entdeckung Amerikas durch Christoph Kolumbus im Jahr 1492 führte zu einem massiven kulturellen Austausch.",
  "Die Französische Revolution begann 1789 mit dem Sturm auf die Bastille.",
  "Der Zweite Weltkrieg endete 1945 mit der Kapitulation Japans.",
  "Die Berliner Mauer fiel 1989 und symbolisierte das Ende des Kalten Krieges.",
  "Die erste Frau im Weltraum war Walentina Tereschkowa im Jahr 1963.",
  "Die Erfindung des Buchdrucks revolutionierte die Verbreitung von Wissen.",
  "Die Seidenstraße war ein Netzwerk von Handelsrouten, das Ost und West verband.",
  "Die Olympischen Spiele wurden ursprünglich im antiken Griechenland abgehalten.",
  "1492 entdeckte Kolumbus Amerika.🧠 Eselsbrücke: \"Vierzehn – neunzig – zwei, Amerika ruft: Juhu!\"",
  "1914 begann der Erste Weltkrieg.🧠 Eselsbrücke: \"14 ist Teeniealter – und die Menschheit benahm sich wie ein unreifer Teenie.\"",
  "In Japan trugen Samurai zwei Schwerter – ein langes Katana und ein kurzes Wakizashi – als Zeichen ihres Standes.",
  "Marie Curie ist die einzige Person, die Nobelpreise in zwei verschiedenen Naturwissenschaften gewonnen hat – Physik und Chemie.",
  "Im 19. Jahrhundert war es in Europa Mode, echte Mumien aus Ägypten zu importieren und bei Dinnerpartys zu 'entrollen'.",
  "Die Chinesen haben Papiergeld schon im 9. Jahrhundert benutzt – lange bevor es im Westen üblich wurde.",
  "Alexander der Große benannte über 20 Städte nach sich – und eine sogar nach seinem Pferd (Bucephala).",
  "Der kürzeste Krieg der Geschichte war zwischen Sansibar und Großbritannien – er dauerte nur 38 Minuten.",
  "Honig ist das einzige Lebensmittel, das niemals verdirbt.",
  "Ein Blitz ist fünfmal heißer als die Oberfläche der Sonne.",
  "Das menschliche Gehirn wiegt etwa 1,4 Kilogramm, verbraucht aber 20% des gesamten Sauerstoffs und der Kalorien des Körpers.",
  "Es gibt mehr Sterne im Universum, als Sandkörner auf allen Stränden der Erde.",
  "Ein Teelöffel Neutronensternmaterie würde eine Milliarde Tonnen wiegen.",
  "Pflanzen können miteinander kommunizieren, indem sie chemische Signale in der Luft freisetzen.",
  "Das Universum dehnt sich aus, und die Galaxien entfernen sich voneinander.",
  "Die Erde dreht sich mit etwa 1.670 Kilometern pro Stunde am Äquator.",
  "Das größte Lebewesen der Welt ist ein Pilz in Oregon, der über 9 Quadratkilometer groß ist.",
  "Wasser kann in drei Aggregatzuständen gleichzeitig existieren: fest, flüssig und gasförmig (Tripelpunkt).",
  "Das Licht der Sonne braucht etwa 8 Minuten und 20 Sekunden, um die Erde zu erreichen.",
  "Haie haben keine Knochen, ihr Skelett besteht aus Knorpel.",
  "Das menschliche Auge kann etwa 10 Millionen verschiedene Farben unterscheiden.",
  "Ein Kolibri ist der einzige Vogel, der rückwärts fliegen kann.",
  "Die DNA in einer einzigen menschlichen Zelle ist etwa 2 Meter lang, wenn sie entrollt wird.",
  "Der Mount Everest wächst jedes Jahr um etwa 4 Millimeter.",
  "Die Schwerkraft auf dem Mond beträgt nur etwa ein Sechstel der Schwerkraft auf der Erde.",
  "Das schnellste Tier der Welt ist der Wanderfalke, der im Sturzflug über 320 km/h erreichen kann.",
  "Bienen kommunizieren durch einen 'Schwänzeltanz', um andere Bienen zu Nahrungsquellen zu führen.",
  "Die Oberfläche der Sonne ist etwa 5.500 Grad Celsius heiß.",
  "Haie bekommen keinen Knochenkrebs, weil sie gar keine Knochen haben – ihr Skelett besteht nur aus Knorpel.",
  "Die ISS umkreist die Erde alle 90 Minuten – das sind 16 Sonnenaufgänge pro Tag für die Astronauten.",
  "Ein Gramm Erde kann mehr lebende Organismen enthalten als es Menschen auf der Erde gibt.",
  "Honig verdirbt nie – man fand in Pharaonengräbern Honig, der noch essbar war.",
  "Elektronen haben keinen festen Ort – sie sind Wahrscheinlichkeitswolken in der Quantenphysik.",
  "Ein Blitz ist heißer als die Oberfläche der Sonne – bis zu 30.000 Grad Celsius.",
  "Delfine geben sich gegenseitig Namen – individuelle Pfeiftöne, die sie selbst erfinden.",
  "Das menschliche Gefäßsystem ist über 100.000 km lang – genug für zweimal um die Erde.",
  "Spinnen können verlorene Beine nachwachsen lassen – bei der nächsten Häutung.",
  "Der Magen verdaut sich nicht selbst, weil er ständig eine neue Schleimschicht bildet.",
  "Eine Gruppe von Eulen wird 'Parlament' genannt.",
  "Erdbeeren sind botanisch gesehen keine Beeren, aber Bananen sind es.",
  "Der Eiffelturm kann im Sommer um bis zu 15 cm wachsen, da sich das Eisen bei Hitze ausdehnt.",
  "Das Geräusch, das man hört, wenn man eine Muschel ans Ohr hält, ist das Geräusch des Blutes, das durch die Gefäße in Ihrem Ohr fließt, nicht das Meer.",
  "Die meisten Lippenstifte enthalten Fischschuppen.",
  "Es ist unmöglich, mit offenen Augen zu niesen.",
  "Das Wort 'Typografie' kommt aus dem Griechischen und bedeutet 'Schriftbild'.",
  "Die Farbe Orange wurde nach der Frucht benannt, nicht umgekehrt.",
  "Der längste englische Wort, der ohne Vokale geschrieben werden kann, ist 'rhythm'.",
  "Die durchschnittliche Wolke wiegt etwa 550 Tonnen.",
  "Krokodile können ihre Zunge nicht herausstrecken.",
  "Ein Faultier braucht zwei Wochen, um seine Nahrung zu verdauen.",
  "Die Zunge eines Blauwals ist so groß wie ein Elefant.",
  "Es gibt mehr künstliche Satelliten im Weltraum als echte Sterne, die man mit bloßem Auge sehen kann.",
  "Die Nationalhymne Spaniens hat keinen Text.",
  "Die einzige Zahl, die die gleiche Anzahl von Buchstaben wie ihr Wert hat, ist 'vier'.",
  "Ein Kamel kann bis zu 100 Liter Wasser in nur 10 Minuten trinken.",
  "Die längste aufgezeichnete Flugzeit eines Huhns beträgt 13 Sekunden.",
  "Die Farbe des Himmels ist blau, weil das Sonnenlicht in der Atmosphäre gestreut wird.",
  "Die meisten Menschen blinzeln etwa 15-20 Mal pro Minute.",
  "In Japan gibt es mehr Haustiere als Kinder.",
  "Die meisten Menschen träumen etwa zwei Stunden pro Nacht – auch wenn sie sich nie daran erinnern.",
  "Der Kleber auf Briefmarken enthält Kalorien.",
  "Oxford University ist älter als die Azteken.",
  "Das Wort 'Alphabet' stammt von den ersten zwei griechischen Buchstaben: Alpha und Beta.",
  "In Frankreich ist es gesetzlich verboten, ein Schwein Napoleon zu nennen.",
  "Die Wahrscheinlichkeit, von einem Automaten erschlagen zu werden, ist höher als von einem Hai getötet zu werden.",
  "Ketchup wurde früher als Medizin verkauft.",
  "In Schottland gibt es 421 Wörter für 'Schnee'.",
  "Wombats machen eckigen Kot – damit er nicht wegrollt.",
  "Erdgas ist der sauberste fossile Brennstoff und verbrennt mit geringeren CO2-Emissionen als Kohle oder Öl.",
  "Strom bewegt sich mit Lichtgeschwindigkeit, also etwa 300.000 Kilometer pro Sekunde.",
  "Die erste öffentliche Stromversorgung wurde 1882 von Thomas Edison in New York City eingerichtet.",
  "Ein durchschnittlicher deutscher Haushalt verbraucht jährlich etwa 2.500 bis 5.000 kWh Strom.",
  "Die Maßeinheit für elektrische Leistung ist Watt (W), benannt nach James Watt.",
  "Der Wirkungsgrad von Glühbirnen liegt bei nur etwa 5-10%, der Rest wird zu Wärme.",
];

const questionsAnswersData: QuestionAnswerReward[] = [
  { question: "Was ist die Hauptstadt von Australien?", answer: "Canberra" },
  { question: "Was ist die Hauptstadt von Kanada?", answer: "Ottawa" },
  { question: "Was ist die Hauptstadt von Brasilien?", answer: "Brasília" },
  { question: "Was ist die Hauptstadt von Südafrika?", answer: "Pretoria (Verwaltung), Kapstadt (Legislative), Bloemfontein (Judikative)" },
  { question: "Was ist die Hauptstadt von Ägypten?", answer: "Kairo" },
  { question: "Was ist die Hauptstadt von Neuseeland?", answer: "Wellington" },
  { question: "Was ist die Hauptstadt von Argentinien?", answer: "Buenos Aires" },
  { question: "Was ist die Hauptstadt von Indien?", answer: "Neu-Delhi" },
  { question: "Was ist die Hauptstadt von Japan?", answer: "Tokio" },
  { question: "Was ist die Hauptstadt von Mexiko?", answer: "Mexiko-Stadt" },
  { question: "Was ist die Hauptstadt von Deutschland?", answer: "Berlin" },
  { question: "Was ist die Hauptstadt von Frankreich?", answer: "Paris" },
  { question: "Was ist die Hauptstadt von Italien?", answer: "Rom" },
  { question: "Was ist die Hauptstadt von Spanien?", answer: "Madrid" },
  { question: "Was ist die Hauptstadt des Vereinigten Königreichs?", answer: "London" },
  { question: "Was ist die Hauptstadt der Vereinigten Staaten?", answer: "Washington, D.C." },
  { question: "Was ist die Hauptstadt von China?", answer: "Peking" },
  { question: "Was ist die Hauptstadt von Russland?", answer: "Moskau" },
  { question: "Was ist die Hauptstadt von Südkorea?", answer: "Seoul" },
  { question: "Was ist die Hauptstadt von Indonesien?", answer: "Jakarta" },
  { question: "Was ist die Hauptstadt von der Türkei?", answer: "Ankara" },
  { question: "Was ist die Hauptstadt von Saudi-Arabien?", answer: "Riad" },
  { question: "Was ist die Hauptstadt von Nigeria?", answer: "Abuja" },
  { question: "Was ist die Hauptstadt von Äthiopien?", answer: "Addis Abeba" },
  { question: "Was ist die Hauptstadt von Kenia?", answer: "Nairobi" },
  { question: "Was ist die Hauptstadt von Peru?", answer: "Lima" },
  { question: "Was ist die Hauptstadt von Kolumbien?", answer: "Bogotá" },
  { question: "Was ist die Hauptstadt von Chile?", answer: "Santiago" },
  { question: "Was ist die Hauptstadt von Schweden?", answer: "Stockholm" },
  { question: "Was ist die Hauptstadt von Norwegen?", answer: "Oslo" },
  { question: "Was ist die Hauptstadt von Dänemark?", answer: "Kopenhagen" },
  { question: "Was ist die Hauptstadt von Finnland?", answer: "Helsinki" },
  { question: "Was ist die Hauptstadt von Polen?", answer: "Warschau" },
  { question: "Was ist die Hauptstadt von der Ukraine?", answer: "Kiew" },
  { question: "Was ist die Hauptstadt von Griechenland?", answer: "Athen" },
  { question: "Was ist die Hauptstadt von Portugal?", answer: "Lissabon" },
  { question: "Was ist die Hauptstadt von Irland?", answer: "Dublin" },
  { question: "Was ist die Hauptstadt von Belgien?", answer: "Brüssel" },
  { question: "Was ist die Hauptstadt der Niederlande?", answer: "Amsterdam" },
  { question: "Was ist die Hauptstadt der Schweiz?", answer: "Bern" },
  { question: "Was ist die Hauptstadt von Österreich?", answer: "Wien" },
  { question: "Was ist die Hauptstadt von Ungarn?", answer: "Budapest" },
  { question: "Was ist die Hauptstadt von Tschechien?", answer: "Prag" },
  { question: "Was ist die Hauptstadt von Vietnam?", answer: "Hanoi" },
  { question: "Was ist die Hauptstadt von Thailand?", answer: "Bangkok" },
  { question: "Was ist die Hauptstadt von Malaysia?", answer: "Kuala Lumpur" },
  { question: "Was ist die Hauptstadt von den Philippinen?", answer: "Manila" },
  { question: "Was ist die Hauptstadt von Pakistan?", answer: "Islamabad" },
  { question: "Was ist die Hauptstadt von Bangladesch?", answer: "Dhaka" },
  { question: "Was ist die Hauptstadt von Iran?", answer: "Teheran" },
  { question: "Was ist die Hauptstadt von Irak?", answer: "Bagdad" },
  { question: "Was ist die Hauptstadt von Afghanistan?", answer: "Kabul" },
  { question: "Was ist die Hauptstadt von Usbekistan?", answer: "Taschkent" },
  { question: "Was ist die Hauptstadt von Kasachstan?", answer: "Nur-Sultan (Astana)" },
  { question: "Was ist die Hauptstadt von Ägypten?", answer: "Kairo" },
  { question: "Was ist die Hauptstadt von Marokko?", answer: "Rabat" },
  { question: "Was ist die Hauptstadt von Algerien?", answer: "Algier" },
  { question: "Was ist die Hauptstadt von Tunesien?", answer: "Tunis" },
  { question: "Was ist die Hauptstadt von Libyen?", answer: "Tripolis" },
  { question: "Was ist die Hauptstadt von Sudan?", answer: "Khartum" },
  { question: "Was ist die Hauptstadt von Südsudan?", answer: "Juba" },
  { question: "Was ist die Hauptstadt von Kongo (Demokratische Republik)?", answer: "Kinshasa" },
  { question: "Was ist die Hauptstadt von Tansania?", answer: "Dodoma" },
  { question: "Was ist die Hauptstadt von Uganda?", answer: "Kampala" },
  { question: "Was ist die Hauptstadt von Ruanda?", answer: "Kigali" },
  { question: "Was ist die Hauptstadt von Burundi?", answer: "Gitega" },
  { question: "Was ist die Hauptstadt von Sambia?", answer: "Lusaka" },
  { question: "Was ist die Hauptstadt von Simbabwe?", answer: "Harare" },
  { question: "Was ist die Hauptstadt von Mosambik?", answer: "Maputo" },
  { question: "Was ist die Hauptstadt von Angola?", answer: "Luanda" },
  { question: "Was ist die Hauptstadt von Namibia?", answer: "Windhoek" },
  { question: "Was ist die Hauptstadt von Botswana?", answer: "Gaborone" },
  { question: "Was ist die Hauptstadt von Madagaskar?", answer: "Antananarivo" },
  { question: "Was ist die Hauptstadt von Venezuela?", answer: "Caracas" },
  { question: "Was ist die Hauptstadt von Ecuador?", answer: "Quito" },
  { question: "Was ist die Hauptstadt von Bolivien?", answer: "Sucre (konstitutionell), La Paz (Regierungssitz)" },
  { question: "Was ist die Hauptstadt von Paraguay?", answer: "Asunción" },
  { question: "Was ist die Hauptstadt von Uruguay?", answer: "Montevideo" },
  { question: "Was ist die Hauptstadt von Kuba?", answer: "Havanna" },
  { question: "Was ist die Hauptstadt der Dominikanischen Republik?", answer: "Santo Domingo" },
  { question: "Was ist die Hauptstadt von Haiti?", answer: "Port-au-Prince" },
  { question: "Was ist die Hauptstadt von Guatemala?", answer: "Guatemala-Stadt" },
  { question: "Was ist die Hauptstadt von Honduras?", answer: "Tegucigalpa" },
  { question: "Was ist die Hauptstadt von El Salvador?", answer: "San Salvador" },
  { question: "Was ist die Hauptstadt von Nicaragua?", answer: "Managua" },
  { question: "Was ist die Hauptstadt von Costa Rica?", answer: "San José" },
  { question: "Was ist die Hauptstadt von Panama?", answer: "Panama-Stadt" },
  { question: "Was ist die Hauptstadt von Australien?", answer: "Canberra" },
  { question: "Was ist die Hauptstadt von Fidschi?", answer: "Suva" },
  { question: "Was ist die Hauptstadt von Papua-Neuguinea?", answer: "Port Moresby" },
  { question: "Was ist die Hauptstadt von Afghanistan?", answer: "Kabul" },
  { question: "Was ist die Hauptstadt von Armenien?", answer: "Jerewan" },
  { question: "Was ist die Hauptstadt von Aserbaidschan?", answer: "Baku" },
  { question: "Was ist die Hauptstadt von Georgien?", answer: "Tiflis" },
  { question: "Was ist die Hauptstadt von Jordanien?", answer: "Amman" },
  { question: "Was ist die Hauptstadt von Libanon?", answer: "Beirut" },
  { question: "Was ist die Hauptstadt von Syrien?", answer: "Damaskus" },
  { question: "Was ist die Hauptstadt von Israel?", answer: "Jerusalem" },
  { question: "Was ist die Hauptstadt von Palästina?", answer: "Ramallah (Verwaltung), Ost-Jerusalem (beansprucht)" },
  { question: "Was ist die Hauptstadt von Zypern?", answer: "Nikosia" },
  { question: "Was ist die Hauptstadt von Malta?", answer: "Valletta" },
  { question: "Was ist die Hauptstadt von Island?", answer: "Reykjavík" },
  { question: "Was ist die Hauptstadt von Estland?", answer: "Tallinn" },
  { question: "Was ist die Hauptstadt von Lettland?", answer: "Riga" },
  { question: "Was ist die Hauptstadt von Litauen?", answer: "Vilnius" },
  { question: "Was ist die Hauptstadt von Belarus?", answer: "Minsk" },
  { question: "Was ist die Hauptstadt von Moldawien?", answer: "Chișinău" },
  { question: "Was ist die Hauptstadt von Rumänien?", answer: "Bukarest" },
  { question: "Was ist die Hauptstadt von Bulgarien?", answer: "Sofia" },
  { question: "Was ist die Hauptstadt von Serbien?", answer: "Belgrad" },
  { question: "Was ist die Hauptstadt von Kroatien?", answer: "Zagreb" },
  { question: "Was ist die Hauptstadt von Bosnien und Herzegowina?", answer: "Sarajevo" },
  { question: "Was ist die Hauptstadt von Montenegro?", answer: "Podgorica" },
  { question: "Was ist die Hauptstadt von Albanien?", answer: "Tirana" },
  { question: "Was ist die Hauptstadt von Nordmazedonien?", answer: "Skopje" },
  { question: "Was ist die Hauptstadt von Kosovo?", answer: "Pristina" },
  { question: "Was ist die Hauptstadt von Slowenien?", answer: "Ljubljana" },
  { question: "Was ist die Hauptstadt von der Slowakei?", answer: "Bratislava" },
  { question: "Was ist die Hauptstadt von der Mongolei?", answer: "Ulaanbaatar" },
  { question: "Was ist die Hauptstadt von Nepal?", answer: "Kathmandu" },
  { question: "Was ist die Hauptstadt von Sri Lanka?", answer: "Sri Jayawardenepura Kotte (Legislative), Colombo (Exekutive und Judikative)" },
  { question: "Was ist die Hauptstadt von Myanmar?", answer: "Naypyidaw" },
  { question: "Was ist die Hauptstadt von Laos?", answer: "Vientiane" },
  { question: "Was ist die Hauptstadt von Kambodscha?", answer: "Phnom Penh" },
  { question: "Was ist die Hauptstadt von Singapur?", answer: "Singapur" },
  { question: "Was ist die Hauptstadt von Brunei?", answer: "Bandar Seri Begawan" },
  { question: "Was ist die Hauptstadt von Osttimor?", answer: "Dili" },
];

const vocabularyData: VocabularyReward[] = [
  { question: "I would like to report my current meter reading.", answer: "Ich möchte meinen aktuellen Zählerstand mitteilen." },
  { question: "The meter reading on the bill does not match my actual consumption.", answer: "Der Zählerstand auf der Rechnung stimmt nicht mit meinem tatsächlichen Verbrauch überein." },
  { question: "My monthly installment is too high compared to my usage.", answer: "Mein monatlicher Abschlag ist im Vergleich zu meinem Verbrauch zu hoch." },
  { question: "I want to lower my monthly payment for electricity.", answer: "Ich möchte meinen monatlichen Abschlagsbetrag für Strom senken." },
  { question: "There is an error in my final annual statement.", answer: "In meiner Jahresabschlussrechnung ist ein Fehler." },
  { question: "I have not received my credit note from the last billing period yet.", answer: "Ich habe mein Guthaben aus der letzten Abrechnungsperiode noch nicht erhalten." },
  { question: "Why has my basic price increased so significantly?", answer: "Warum hat sich mein Grundpreis so stark erhöht?" },
  { question: "I want to object to this invoice.", answer: "Ich möchte Widerspruch gegen diese Rechnung einlegen." },
  { question: "My gas meter was replaced last month.", answer: "Mein Gaszähler wurde letzten Monat ausgetauscht." },
  { question: "I am moving and would like to cancel my contract.", answer: "Ich ziehe um und möchte meinen Vertrag kündigen." },
  { question: "Could you please check if my price guarantee is still valid?", answer: "Könnten Sie bitte prüfen, ob meine Preisgarantie noch gültig ist?" },
  { question: "I received a reminder even though I have already paid.", answer: "Ich habe eine Mahnung erhalten, obwohl ich bereits bezahlt habe." },
  { question: "The estimated consumption is much higher than what I actually used.", answer: "Der geschätzte Verbrauch ist viel höher als mein tatsächlicher Verbrauch." },
  { question: "I would like to switch my electricity provider due to the price increase.", answer: "Ich möchte wegen der Preiserhöhung meinen Stromanbieter wechseln." },
  { question: "Where can I find my customer number and contract account?", answer: "Wo finde ich meine Kundennummer und mein Vertragskonto?" },
  { question: "Is there a bonus for new customers in this tariff?", answer: "Gibt es in diesem Tarif einen Neukundenbonus?" },
  { question: "I am exercising my special right of termination due to the price increase.", answer: "Ich mache von meinem Sonderkündigungsrecht wegen der Preiserhöhung Gebrauch." },
  { question: "When will the smart meter be installed in my apartment?", answer: "Wann wird der intelligente Zähler in meiner Wohnung installiert?" },
  { question: "The price increase is not transparent to me.", answer: "Die Preiserhöhung ist für mich nicht transparent nachvollziehbar." },
  { question: "Can I track my real-time consumption with the new smart meter?", answer: "Kann ich mit dem neuen Smart Meter meinen Verbrauch in Echtzeit verfolgen?" },
  { question: "I didn't receive a notification about the price change in time.", answer: "Ich habe die Mitteilung über die Preisänderung nicht rechtzeitig erhalten." },
  { question: "My bank details have changed for the SEPA direct debit.", answer: "Meine Bankverbindung für das SEPA-Lastschriftmandat hat sich geändert." },
  { question: "I want to request a verification of the meter because it seems defective.", answer: "Ich möchte eine Befundprüfung des Zählers beantragen, da er defekt zu sein scheint." },
  { question: "The bonus for switching was not deducted from my bill.", answer: "Der Wechselbonus wurde nicht von meiner Rechnung abgezogen." },
  { question: "Is there an additional fee for the installation of the smart meter?", answer: "Fällt für den Einbau des Smart Meters eine zusätzliche Gebühr an?" },
  { question: "I disagree with the estimated billing; please use my actual reading.", answer: "Ich bin mit der Schätzung nicht einverstanden; bitte nutzen Sie meinen tatsächlichen Zählerstand." },
  { question: "What is the notice period if I want to switch to a cheaper provider?", answer: "Wie lang ist die Kündigungsfrist, wenn ich zu einem günstigeren Anbieter wechseln möchte?" },
  { question: "My advance payment was increased without any change in my consumption behavior.", answer: "Mein Abschlag wurde erhöht, ohne dass sich mein Verbrauchsverhalten geändert hat." },
  { question: "I have a credit balance of two hundred euros on my account.", answer: "Ich habe ein Guthaben von zweihundert Euro auf meinem Konto." },
  { question: "Does the price guarantee cover all components of the electricity price?", answer: "Bezieht sich die Preisgarantie auf alle Bestandteile des Strompreises?" },
  { question: "I would like to receive my invoices by email instead of by post.", answer: "Ich möchte meine Rechnungen per E-Mail statt per Post erhalten." },
  { question: "The transfer of my data to the new provider did not work.", answer: "Die Datenübermittlung an den neuen Versorger hat nicht funktioniert." },
  { question: "I would like to request a payment plan for the additional payment.", answer: "Ich möchte eine Ratenzahlung für die Nachzahlung vereinbaren." },
  { question: "The meter number on my contract does not match the one in the basement.", answer: "Die Zählernummer in meinem Vertrag stimmt nicht mit der im Keller überein." },
  { question: "Why was my loyalty bonus not applied to the final bill?", answer: "Warum wurde mein Treuebonus nicht in der Schlussrechnung berücksichtigt?" },
  { question: "I would like to revoke my contract within the fourteen-day cancellation period.", answer: "Ich möchte meinen Vertrag innerhalb der vierzehntägigen Widerrufsfrist widerrufen." },
  { question: "There is a mistake in the calculation of the value-added tax.", answer: "Bei der Berechnung der Mehrwertsteuer ist ein Fehler unterlaufen." },
  { question: "My electricity was cut off despite my previous payment.", answer: "Mein Strom wurde gesperrt, obwohl ich bereits gezahlt habe." },
  { question: "I need a confirmation of the termination for my new provider.", answer: "Ich benötige eine Kündigungsbestätigung für meinen neuen Versorger." },
  { question: "The solar feed-in was not correctly offset against my consumption.", answer: "Die PV-Einspeisung wurde nicht korrekt mit meinem Verbrauch verrechnet." },
  { question: "Who is responsible for the maintenance of the gas connection?", answer: "Wer ist für die Wartung des Gasanschlusses zuständig?" },
  { question: "My consumption has doubled, but I haven't changed my appliances.", answer: "Mein Verbrauch hat sich verdoppelt, aber ich habe keine neuen Geräte." },
  { question: "I am being billed for a period when I didn't even live in the apartment.", answer: "Mir wird ein Zeitraum berechnet, in dem ich noch gar nicht in der Wohnung gewohnt habe." },
  { question: "The grid operator has not yet confirmed my meter reading.", answer: "Der Netzbetreiber hat meinen Zählerstand noch nicht bestätigt." },
  { question: "Is this a fixed price or a dynamic electricity tariff?", answer: "Handelt es sich hierbei um einen Festpreis oder einen dynamischen Stromtarif?" },
  { question: "I want to change the date of the monthly direct debit.", answer: "Ich möchte den Termin für den monatlichen Lastschrifteinzug ändern." },
  { question: "Please send me a detailed breakdown of the price components.", answer: "Bitte senden Sie mir eine detaillierte Aufschlüsselung der Preisbestandteile." },
  { question: "I am moving abroad and want to terminate my contract prematurely.", answer: "Ich ziehe ins Ausland und möchte meinen Vertrag vorzeitig kündigen." },
  { question: "The handover protocol clearly shows a different meter reading.", answer: "Das Übergabeprotokoll zeigt eindeutig einen anderen Zählerstand." },
  { question: "I am still waiting for the refund of my overpayment.", answer: "Ich warte noch immer auf die Rückerstattung meiner Überzahlung." },
  { question: "Ich möchte meinen aktuellen Zählerstand mitteilen.", answer: "I would like to report my current meter reading." },
  { question: "Der Zählerstand auf der Rechnung stimmt nicht mit meinem tatsächlichen Verbrauch überein.", answer: "The meter reading on the bill does not match my actual consumption." },
  { question: "Mein monatlicher Abschlag ist im Vergleich zu meinem Verbrauch zu hoch.", answer: "My monthly installment is too high compared to my usage." },
  { question: "Ich möchte meinen monatlichen Abschlagsbetrag für Strom senken.", answer: "I want to lower my monthly payment for electricity." },
  { question: "In meiner Jahresabschlussrechnung ist ein Fehler.", answer: "There is an error in my final annual statement." },
  { question: "Ich habe mein Guthaben aus der letzten Abrechnungsperiode noch nicht erhalten.", answer: "I have not received my credit note from the last billing period yet." },
  { question: "Warum hat sich mein Grundpreis so stark erhöht?", answer: "Why has my basic price increased so significantly?" },
  { question: "Ich möchte Widerspruch gegen diese Rechnung einlegen.", answer: "I want to object to this invoice." },
  { question: "Mein Gaszähler wurde letzten Monat ausgetauscht.", answer: "My gas meter was replaced last month." },
  { question: "Ich ziehe um und möchte meinen Vertrag kündigen.", answer: "I am moving and would like to cancel my contract." },
  { question: "Könnten Sie bitte prüfen, ob meine Preisgarantie noch gültig ist?", answer: "Could you please check if my price guarantee is still valid?" },
  { question: "Ich habe eine Mahnung erhalten, obwohl ich bereits bezahlt habe.", answer: "I received a reminder even though I have already paid." },
  { question: "Der geschätzte Verbrauch ist viel höher als mein tatsächlicher Verbrauch.", answer: "The estimated consumption is much higher than what I actually used." },
  { question: "Ich möchte wegen der Preiserhöhung meinen Stromanbieter wechseln.", answer: "I would like to switch my electricity provider due to the price increase." },
  { question: "Wo finde ich meine Kundennummer und mein Vertragskonto?", answer: "Where can I find my customer number and contract account?" },
  { question: "Gibt es in diesem Tarif einen Neukundenbonus?", answer: "Is there a bonus for new customers in this tariff?" },
  { question: "Ich mache von meinem Sonderkündigungsrecht wegen der Preiserhöhung Gebrauch.", answer: "I am exercising my special right of termination due to the price increase." },
  { question: "Wann wird der intelligente Zähler in meiner Wohnung installiert?", answer: "When will the smart meter be installed in my apartment?" },
  { question: "Die Preiserhöhung ist für mich nicht transparent nachvollziehbar.", answer: "The price increase is not transparent to me." },
  { question: "Kann ich mit dem neuen Smart Meter meinen Verbrauch in Echtzeit verfolgen?", answer: "Can I track my real-time consumption with the new smart meter?" },
  { question: "Ich habe die Mitteilung über die Preisänderung nicht rechtzeitig erhalten.", answer: "I didn't receive a notification about the price change in time." },
  { question: "Meine Bankverbindung für das SEPA-Lastschriftmandat hat sich geändert.", answer: "My bank details have changed for the SEPA direct debit." },
  { question: "Ich möchte eine Befundprüfung des Zählers beantragen, da er defekt zu sein scheint.", answer: "I want to request a verification of the meter because it seems defective." },
  { question: "Der Wechselbonus wurde nicht von meiner Rechnung abgezogen.", answer: "The bonus for switching was not deducted from my bill." },
  { question: "Fällt für den Einbau des Smart Meters eine zusätzliche Gebühr an?", answer: "Is there an additional fee for the installation of the smart meter?" },
  { question: "Ich bin mit der Schätzung nicht einverstanden; bitte nutzen Sie meinen tatsächlichen Zählerstand.", answer: "I disagree with the estimated billing; please use my actual reading." },
  { question: "Wie lang ist die Kündigungsfrist, wenn ich zu einem günstigeren Anbieter wechseln möchte?", answer: "What is the notice period if I want to switch to a cheaper provider?" },
  { question: "Mein Abschlag wurde erhöht, ohne dass sich mein Verbrauchsverhalten geändert hat.", answer: "My advance payment was increased without any change in my consumption behavior." },
  { question: "Ich habe ein Guthaben von zweihundert Euro auf meinem Konto.", answer: "I have a credit balance of two hundred euros on my account." },
  { question: "Bezieht sich die Preisgarantie auf alle Bestandteile des Strompreises?", answer: "Does the price guarantee cover all components of the electricity price?" },
  { question: "Ich möchte meine Rechnungen per E-Mail statt per Post erhalten.", answer: "I would like to receive my invoices by email instead of by post." },
  { question: "Die Datenübermittlung an den neuen Versorger hat nicht funktioniert.", answer: "The transfer of my data to the new provider did not work." },
  { question: "Ich möchte eine Ratenzahlung für die Nachzahlung vereinbaren.", answer: "I would like to request a payment plan for the additional payment." },
  { question: "Die Zählernummer in meinem Vertrag stimmt nicht mit der im Keller überein.", answer: "The meter number on my contract does not match the one in the basement." },
  { question: "Warum wurde mein Treuebonus nicht in der Schlussrechnung berücksichtigt?", answer: "Why was my loyalty bonus not applied to the final bill?" },
  { question: "Ich möchte meinen Vertrag innerhalb der vierzehntägigen Widerrufsfrist widerrufen.", answer: "I would like to revoke my contract within the fourteen-day cancellation period." },
  { question: "Bei der Berechnung der Mehrwertsteuer ist ein Fehler unterlaufen.", answer: "There is a mistake in the calculation of the value-added tax." },
  { question: "Mein Strom wurde gesperrt, obwohl ich bereits gezahlt habe.", answer: "My electricity was cut off despite my previous payment." },
  { question: "Ich benötige eine Kündigungsbestätigung für meinen neuen Versorger.", answer: "I need a confirmation of the termination for my new provider." },
  { question: "Die PV-Einspeisung wurde nicht korrekt mit meinem Verbrauch verrechnet.", answer: "The solar feed-in was not correctly offset against my consumption." },
  { question: "Wer ist für die Wartung des Gasanschlusses zuständig?", answer: "Who is responsible for the maintenance of the gas connection?" },
  { question: "Mein Verbrauch hat sich verdoppelt, aber ich habe keine neuen Geräte.", answer: "My consumption has doubled, but I haven't changed my appliances." },
  { question: "Mir wird ein Zeitraum berechnet, in dem ich noch gar nicht in der Wohnung gewohnt habe.", answer: "I am being billed for a period when I didn't even live in the apartment." },
  { question: "Der Netzbetreiber hat meinen Zählerstand noch nicht bestätigt.", answer: "The grid operator has not yet confirmed my meter reading." },
  { question: "Handelt es sich hierbei um einen Festpreis oder einen dynamischen Stromtarif?", answer: "Is this a fixed price or a dynamic electricity tariff?" },
  { question: "Ich möchte den Termin für den monatlichen Lastschrifteinzug ändern.", answer: "I want to change the date of the monthly direct debit." },
  { question: "Bitte senden Sie mir eine detaillierte Aufschlüsselung der Preisbestandteile.", answer: "Please send me a detailed breakdown of the price components." },
  { question: "Ich ziehe ins Ausland und möchte meinen Vertrag vorzeitig kündigen.", answer: "I am moving abroad and want to terminate my contract prematurely." },
  { question: "Das Übergabeprotokoll zeigt eindeutig einen anderen Zählerstand.", answer: "The handover protocol clearly shows a different meter reading." },
  { question: "Ich warte noch immer auf die Rückerstattung meiner Überzahlung.", answer: "I am still waiting for the refund of my overpayment." },
  { question: "Können Sie mir den aktuellen Arbeitspreis pro Kilowattstunde nennen?", answer: "Can you tell me the current price per kilowatt-hour?" },
  { question: "Ich habe den Anbieter gewechselt, aber die Belieferung hat noch nicht begonnen.", answer: "I switched providers, but the supply has not started yet." },
  { question: "Gibt es eine Deckelung für die Energiekosten in diesem Vertrag?", answer: "Is there a cap on energy costs in this contract?" },
];


const flagData: FlagReward[] = [
  { countryName: "Albanien", flagCode: "al" },
  { countryName: "Deutschland", flagCode: "de" },
  { countryName: "Frankreich", flagCode: "fr" },
  { countryName: "Italien", flagCode: "it" },
  { countryName: "Spanien", flagCode: "es" },
  { countryName: "Vereinigte Staaten", flagCode: "us" },
  { countryName: "Kanada", flagCode: "ca" },
  { countryName: "Mexiko", flagCode: "mx" },
  { countryName: "Brasilien", flagCode: "br" },
  { countryName: "Argentinien", flagCode: "ar" },
  { countryName: "Australien", flagCode: "au" },
  { countryName: "Neuseeland", flagCode: "nz" },
  { countryName: "Japan", flagCode: "jp" },
  { countryName: "China", flagCode: "cn" },
  { countryName: "Indien", flagCode: "in" },
  { countryName: "Südkorea", flagCode: "kr" },
  { countryName: "Russland", flagCode: "ru" },
  { countryName: "Vereinigtes Königreich", flagCode: "gb" },
  { countryName: "Schweiz", flagCode: "ch" },
  { countryName: "Österreich", flagCode: "at" },
  { countryName: "Niederlande", flagCode: "nl" },
  { countryName: "Belgien", flagCode: "be" },
  { countryName: "Schweden", flagCode: "se" },
  { countryName: "Norwegen", flagCode: "no" },
  { countryName: "Dänemark", flagCode: "dk" },
  { countryName: "Finnland", flagCode: "fi" },
  { countryName: "Polen", flagCode: "pl" },
  { countryName: "Ukraine", flagCode: "ua" },
  { countryName: "Griechenland", flagCode: "gr" },
  { countryName: "Portugal", flagCode: "pt" },
  { countryName: "Irland", flagCode: "ie" },
  { countryName: "Ägypten", flagCode: "eg" },
  { countryName: "Südafrika", flagCode: "za" },
  { countryName: "Nigeria", flagCode: "ng" },
  { countryName: "Kenia", flagCode: "ke" },
  { countryName: "Marokko", flagCode: "ma" },
  { countryName: "Türkei", flagCode: "tr" },
  { countryName: "Saudi-Arabien", flagCode: "sa" },
  { countryName: "Thailand", flagCode: "th" },
  { countryName: "Vietnam", flagCode: "vn" },
  { countryName: "Indonesien", flagCode: "id" },
  { countryName: "Philippinen", flagCode: "ph" },
  { countryName: "Singapur", flagCode: "sg" },
  { countryName: "Malaysia", flagCode: "my" },
  { countryName: "Israel", flagCode: "il" },
  { countryName: "Äthiopien", flagCode: "et" },
  { countryName: "Kolumbien", flagCode: "co" },
  { countryName: "Peru", flagCode: "pe" },
  { countryName: "Chile", flagCode: "cl" },
  { countryName: "Venezuela", flagCode: "ve" },
  { countryName: "Kuba", flagCode: "cu" },
  { countryName: "Tschechien", flagCode: "cz" },
  { countryName: "Ungarn", flagCode: "hu" },
  { countryName: "Rumänien", flagCode: "ro" },
  { countryName: "Bulgarien", flagCode: "bg" },
  { countryName: "Kroatien", flagCode: "hr" },
  { countryName: "Serbien", flagCode: "rs" },
  { countryName: "Bosnien und Herzegowina", flagCode: "ba" },
  { countryName: "Slowenien", flagCode: "si" },
  { countryName: "Slowakei", flagCode: "sk" },
  { countryName: "Litauen", flagCode: "lt" },
  { countryName: "Lettland", flagCode: "lv" },
  { countryName: "Estland", flagCode: "ee" },
  { countryName: "Island", flagCode: "is" },
  { countryName: "Zypern", flagCode: "cy" },
  { countryName: "Malta", flagCode: "mt" },
  { countryName: "Mongolei", flagCode: "mn" },
  { countryName: "Nepal", flagCode: "np" },
  { countryName: "Sri Lanka", flagCode: "lk" },
  { countryName: "Myanmar", flagCode: "mm" },
  { countryName: "Laos", flagCode: "la" },
  { countryName: "Kambodscha", flagCode: "kh" },
  { countryName: "Brunei", flagCode: "bn" },
  { countryName: "Osttimor", flagCode: "tl" },
  { countryName: "Fidschi", flagCode: "fj" },
  { countryName: "Papua-Neuguinea", flagCode: "pg" },
  { countryName: "Afghanistan", flagCode: "af" },
  { countryName: "Armenien", flagCode: "am" },
  { countryName: "Aserbaidschan", flagCode: "az" },
  { countryName: "Georgien", flagCode: "ge" },
  { countryName: "Jordanien", flagCode: "jo" },
  { countryName: "Libanon", flagCode: "lb" },
  { countryName: "Syrien", flagCode: "sy" },
  { countryName: "Palästina", flagCode: "ps" },
  { countryName: "Belarus", flagCode: "by" },
  { countryName: "Moldawien", flagCode: "md" },
  { countryName: "Montenegro", flagCode: "me" },
  { countryName: "Albanien", flagCode: "al" },
  { countryName: "Nordmazedonien", flagCode: "mk" },
  { countryName: "Kosovo", flagCode: "xk" }, // Kosovo uses XK as a temporary code
  { countryName: "Usbekistan", flagCode: "uz" },
  { countryName: "Kasachstan", flagCode: "kz" },
  { countryName: "Algerien", flagCode: "dz" },
  { countryName: "Tunesien", flagCode: "tn" },
  { countryName: "Libyen", flagCode: "ly" },
  { countryName: "Sudan", flagCode: "sd" },
  { countryName: "Südsudan", flagCode: "ss" },
  { countryName: "Kongo (Demokratische Republik)", flagCode: "cd" },
  { countryName: "Tansania", flagCode: "tz" },
  { countryName: "Uganda", flagCode: "ug" },
  { countryName: "Ruanda", flagCode: "rw" },
  { countryName: "Burundi", flagCode: "bi" },
  { countryName: "Sambia", flagCode: "zm" },
  { countryName: "Simbabwe", flagCode: "zw" },
  { countryName: "Mosambik", flagCode: "mz" },
  { countryName: "Angola", flagCode: "ao" },
  { countryName: "Namibia", flagCode: "na" },
  { countryName: "Botswana", flagCode: "bw" },
  { countryName: "Madagaskar", flagCode: "mg" },
  { countryName: "Ecuador", flagCode: "ec" },
  { countryName: "Bolivien", flagCode: "bo" },
  { countryName: "Paraguay", flagCode: "py" },
  { countryName: "Uruguay", flagCode: "uy" },
  { countryName: "Dominikanische Republik", flagCode: "do" },
  { countryName: "Haiti", flagCode: "ht" },
  { countryName: "Guatemala", flagCode: "gt" },
  { countryName: "Honduras", flagCode: "hn" },
  { countryName: "El Salvador", flagCode: "sv" },
  { countryName: "Nicaragua", flagCode: "ni" },
  { countryName: "Costa Rica", flagCode: "cr" },
  { countryName: "Panama", flagCode: "pa" },
];


const allRewards: { [key in Exclude<RewardType, "randomFactWidget" | "quoteOfTheDayWidget">]: (string | QuestionAnswerReward | FlagReward | VocabularyReward)[] } = {
  facts: allFacts,
  questionsAnswers: questionsAnswersData,
  flags: flagData,
  vocabulary: vocabularyData,
};

export const getRandomReward = (completedSessionsToday: number, exclude?: Reward): Reward => {
  // Fact bonus for the 5th session
  if (completedSessionsToday === 4) {
    return { type: "randomFactWidget", content: null };
  }
  // Quote bonus for the 6th session
  if (completedSessionsToday === 5) {
    return { type: "quoteOfTheDayWidget", content: null };
  }

  const types: Exclude<RewardType, "randomFactWidget" | "quoteOfTheDayWidget">[] = ["facts", "questionsAnswers", "flags", "vocabulary"];
  let randomType: Exclude<RewardType, "randomFactWidget" | "quoteOfTheDayWidget">;
  let randomContent: string | QuestionAnswerReward | FlagReward | VocabularyReward;

  do {
    randomType = types[Math.floor(Math.random() * types.length)];
    const contents = allRewards[randomType];
    randomContent = contents[Math.floor(Math.random() * contents.length)];
  } while (exclude && randomType === exclude.type && JSON.stringify(randomContent) === JSON.stringify(exclude.content));

  return { type: randomType, content: randomContent };
};